database:
  engine: "sqlite:////home/brendal4/Documents/LSST/DBB_dev/sqlite.db"
  echo: false
  pool_type: QueuePool
handoff:
  buffer: /home/brendal4/Documents/LSST/handoff_manager/buffer
  holding: /home/brendal4/Documents/LSST/handoff_manager/holding
endpoint:
  user: brendal4
  host: lsst-login03.ncsa.illinois.edu
  buffer: /home/brendal4/data/endpoint/buffer
  staging: /home/brendal4/data/endpoint/staging
  commands:
    remote: "ssh {user}@{host} \"{command}\""
    transfer: "scp -Bq {file} {user}@{host}:{dest}"
logging:
  format: "%(asctime)s:%(name)s:%(levelname)s:%(message)s"
  file: null
  level: INFO
general:
  chunk_size: 1
  timeout: null
  num_threads: 1
  expiration_time: 86400
  pause: 1
  exclude_list:
     # - '\.temp'
